#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pillow
Version  : 9.0.0
Release  : 88
URL      : https://files.pythonhosted.org/packages/b0/43/3e286c93b9fa20e233d53532cc419b5aad8a468d91065dbef4c846058834/Pillow-9.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/b0/43/3e286c93b9fa20e233d53532cc419b5aad8a468d91065dbef4c846058834/Pillow-9.0.0.tar.gz
Summary  : Python Imaging Library (Fork)
Group    : Development/Tools
License  : Apache-2.0 HPND MIT NTP OFL-1.0
Requires: pypi-pillow-license = %{version}-%{release}
Requires: pypi-pillow-python = %{version}-%{release}
Requires: pypi-pillow-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : freetype-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : pypi(black)
BuildRequires : pypi(check_manifest)
BuildRequires : pypi(coverage)
BuildRequires : pypi(defusedxml)
BuildRequires : pypi(olefile)
BuildRequires : pypi(packaging)
BuildRequires : pypi(pyroma)
BuildRequires : pypi(sphinx_copybutton)
BuildRequires : pypi(sphinx_rtd_theme)
Patch1: 0001-Fix-build-Add-default-libdir.patch

%description
<p align="center">
<img width="248" height="250" src="https://raw.githubusercontent.com/python-pillow/pillow-logo/main/pillow-logo-248x250.png" alt="Pillow logo">
</p>

%package license
Summary: license components for the pypi-pillow package.
Group: Default

%description license
license components for the pypi-pillow package.


%package python
Summary: python components for the pypi-pillow package.
Group: Default
Requires: pypi-pillow-python3 = %{version}-%{release}

%description python
python components for the pypi-pillow package.


%package python3
Summary: python3 components for the pypi-pillow package.
Group: Default
Requires: python3-core
Provides: pypi(pillow)
Requires: pypi(black)
Requires: pypi(check_manifest)
Requires: pypi(coverage)
Requires: pypi(defusedxml)
Requires: pypi(olefile)
Requires: pypi(packaging)
Requires: pypi(pyroma)
Requires: pypi(sphinx_copybutton)
Requires: pypi(sphinx_rtd_theme)

%description python3
python3 components for the pypi-pillow package.


%prep
%setup -q -n Pillow-9.0.0
cd %{_builddir}/Pillow-9.0.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1642006292
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pillow
cp %{_builddir}/Pillow-9.0.0/Tests/fonts/DejaVuSans/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-pillow/3d95e2c3b731545390f6888a3214cf7b51fb7971
cp %{_builddir}/Pillow-9.0.0/Tests/fonts/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-pillow/9deb27f8f5fea69a2ab1624ed0698a0c8168ed49
cp %{_builddir}/Pillow-9.0.0/Tests/icc/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-pillow/371117588643c602bb8f15b280424e938c34c369
cp %{_builddir}/Pillow-9.0.0/src/thirdparty/raqm/COPYING %{buildroot}/usr/share/package-licenses/pypi-pillow/b321c557da16c1b66cb89d4a90fa63b5800966cb
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pillow/371117588643c602bb8f15b280424e938c34c369
/usr/share/package-licenses/pypi-pillow/3d95e2c3b731545390f6888a3214cf7b51fb7971
/usr/share/package-licenses/pypi-pillow/9deb27f8f5fea69a2ab1624ed0698a0c8168ed49
/usr/share/package-licenses/pypi-pillow/b321c557da16c1b66cb89d4a90fa63b5800966cb

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
