#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-pillow
Version  : 10.0.1
Release  : 109
URL      : https://files.pythonhosted.org/packages/64/9e/7e638579cce7dc346632f020914141a164a872be813481f058883ee8d421/Pillow-10.0.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/64/9e/7e638579cce7dc346632f020914141a164a872be813481f058883ee8d421/Pillow-10.0.1.tar.gz
Summary  : Python Imaging Library (Fork)
Group    : Development/Tools
License  : Apache-2.0 HPND MIT NTP OFL-1.0
Requires: pypi-pillow-license = %{version}-%{release}
Requires: pypi-pillow-python = %{version}-%{release}
Requires: pypi-pillow-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : freetype-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : pkgconfig(zlib)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(wheel)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Fix-build-Add-default-libdir.patch

%description
<p align="center">
<img width="248" height="250" src="https://raw.githubusercontent.com/python-pillow/pillow-logo/main/pillow-logo-248x250.png" alt="Pillow logo">
</p>

%package license
Summary: license components for the pypi-pillow package.
Group: Default

%description license
license components for the pypi-pillow package.


%package python
Summary: python components for the pypi-pillow package.
Group: Default
Requires: pypi-pillow-python3 = %{version}-%{release}

%description python
python components for the pypi-pillow package.


%package python3
Summary: python3 components for the pypi-pillow package.
Group: Default
Requires: python3-core
Provides: pypi(pillow)

%description python3
python3 components for the pypi-pillow package.


%prep
%setup -q -n Pillow-10.0.1
cd %{_builddir}/Pillow-10.0.1
%patch -P 1 -p1
pushd ..
cp -a Pillow-10.0.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1694800043
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-pillow
cp %{_builddir}/Pillow-%{version}/Tests/fonts/DejaVuSans/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-pillow/3d95e2c3b731545390f6888a3214cf7b51fb7971 || :
cp %{_builddir}/Pillow-%{version}/Tests/fonts/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-pillow/5a20a10da0dd9e25c9581d944c81ae9c2b16b127 || :
cp %{_builddir}/Pillow-%{version}/Tests/icc/LICENSE.txt %{buildroot}/usr/share/package-licenses/pypi-pillow/371117588643c602bb8f15b280424e938c34c369 || :
cp %{_builddir}/Pillow-%{version}/src/thirdparty/raqm/COPYING %{buildroot}/usr/share/package-licenses/pypi-pillow/980792cb6c68c2cf5bb7181d40ec635a1195ed8a || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-pillow/371117588643c602bb8f15b280424e938c34c369
/usr/share/package-licenses/pypi-pillow/3d95e2c3b731545390f6888a3214cf7b51fb7971
/usr/share/package-licenses/pypi-pillow/5a20a10da0dd9e25c9581d944c81ae9c2b16b127
/usr/share/package-licenses/pypi-pillow/980792cb6c68c2cf5bb7181d40ec635a1195ed8a

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/V3/usr/lib/python3*/*
/usr/lib/python3*/*
